# Site
repository: 
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 이하니
title: Java & Spring 백엔드 엔지니어 
email: rorean@naver.com
website: https://blog.naver.com/rorean

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  leehani
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring 기반의 백엔드 개발자로 API 개발 및 웹 개발 경험이 있습니다. 주로 Spring, MySQL, Git 등의 기술을 활용해 개발하고 있습니다. 
  
  기한에 맞춰 개발하는 능력도 중요하지만, 유지 보수성이 높은 코드를 작성하는 능력도 중요하다는걸 깨닫고 더 좋은 코드를 작성하고 개발 문화를 개선하려고 노력하고 있습니다. 

  코드 리뷰에 거부감이 없으며, 코드 안정성을 위해 테스트 커버리지 70% 이상을 목표로 노력하고 있습니다. 

  개발하면서 소통을 중요시합니다. 소통이 잘 되지 않으면 쉬운 일도 어려워질 수 있다는걸 경험하면서 작은 일이라도 서로 맞춰가며 일하는 걸 좋아합니다.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left 
        title: 포커 어드민 
        caption: 2021.06 - 진행중 / nhn soft
        description: | 
          - Spring, MyBatis를 이용해 포커 어드민 개발에 필요한 rest api 개발
          - Vue.js를 이용해 포커 어드민 화면 및 이벤트 페이지 개발 
          - admin 로깅 감사 시스템 연동
      - layout: left 
        title: 신윷놀이2 메인페이지 개발
        caption: 2021.01 - 2021.07 / nhn soft
        description: | 
          - 신윷놀이2 메인 페이지 개발 및 운영
          - 이슈 모니터링 및 이슈 대응 
            - css 깨짐 이슈 수정 
            - 랭킹 서버 장애 대응 경험 
      - layout: left
        title: 위탁 서비스 개발
        caption: 2018.12 - 2019.03 / 체리피카
        description: | 
            - 위탁 판매 서비스 제공에 필요한 REST API 설계 및 개발
            - 반복되는 cs 요청에 위탁 어드민 API 기능 개발
  - title: Experience
    layout: list
    content:
      - layout: left
        title: NHN Soft
        sub_title: 웹개발자
        caption: 2020.8 - 현재
        quote: >
          NHN 한게임 서비스 어드민 개발 및 운영
        description: |
          - 포커 어드민 & 이벤트 개발 및 유지보수
          - 레거시 코드 개선 및 기존 코드 유지보수
          - 테스트 코드 & 코드 리뷰 도입으로 개발 환경 개선
      - layout: left
        title: 체리피카
        sub_title: Java & Spring
        caption: 2018.1 - 2019.12
        quote: >
          중고거래 플랫폼 개발 및 운영. 스타트업 
        description: |
          - 위탁 & 피드 서비스 개발
          - 레거시 코드 개선 및 기존 코드 유지보수 
          - Spring boot, JPA, MySQL 환경에서의 개발 경험 
  - title: Education
    layout: list
    content:
      - layout: left
        title: 삼육대학교
        caption: 2012 ~ 2017
        description: | 
          - 컴퓨터 소프트웨어 전공 학사 졸업
  - title: A Little More About Me
    layout: list
    content:
      - layout: left
        title: JAVA 개발자 양성 과정 이수
        caption: 2016.07 ~ 2016.12
        description: | 
          - 자바 개발 능력, DB 모델링 및 SQL 활용, 웹 프로그래밍, JQuery, AJAX, JSON, Spring Framework, Maven, MyBatis 를 이용하여 전문 개발자 양성 교육 이수 
      - layout: left
        title: 프로젝트 경진대회
        sub_title: 롯데정보통신 경진대회
        caption: 2016.12
        description: | 
          - 금상 수상
          - 앱에서는 iot 기반으로 임산부 배려석을 예약할 수 있고, 어플에 대한 소개 및 소통 할 수 있는 웹 어플리케이션
      - layout: left
        title: 프로젝트 경진대회
        sub_title: 삼육대학교 교내 프로젝트
        caption: 2016.11
        description: | 
          - 대상 수상
          - 1인 가족을 위한 소셜 쉐어링 웹 어플리케이션

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
